name: Build e Teste do Projeto .NET

# 📌 Gatilhos para iniciar o workflow
on:
  push:               # Quando alguém faz push no repositório
  schedule:           # Quando deve rodar automaticamente (cron: minuto, hora, dia, mês, dia-da-semana)
    - cron: '0 * * * *'   # A cada hora (minuto 0 de toda hora)

# 🚀 Definição do job (etapa de execução)
jobs:
  build:
    runs-on: ubuntu-latest   # Ambiente onde o workflow vai rodar

    steps:
      # ✅ Action pré-existente
      - name: Checkout do código
        uses: actions/checkout@v3

      # ✅ Action para instalar o .NET SDK
      - name: Instalar .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # ✅ Script personalizado: restaurar dependências
      - name: Restaurar dependências
        run: dotnet restore

      # ✅ Script personalizado: compilar projeto
      - name: Compilar projeto
        run: dotnet build --no-restore

      # ✅ Script personalizado: rodar testes
      - name: Testar projeto
        run: dotnet test --no-build --verbosity normal

      # ✅ Mensagem personalizada
      - name: Finalização
        run: echo "Workflow finalizado com sucesso!"
