name: Build e Teste do Projeto .NET

on:
  push:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependências
        run: dotnet restore
        working-directory: github4women

      - name: Compilar projeto
        run: dotnet build --no-restore
        working-directory: github4women

      - name: Rodar testes
        run: dotnet test --no-build --verbosity normal
        working-directory: github4women

      - name: Finalização
        run: echo "✅ Workflow concluído com sucesso!"
